import { CategoryItem } from "../../src/types";

export const categories: CategoryItem[] = [
  {
    id: "1",
    title: "Tài liệu",
    color: "#4A90E2",
    icon: "document-text",
    description: "Quản lý và truy cập tài liệu",
    hasSubcategories: true,
    allowUpload: true,
    keyName: "tailieu",
  },
  {
    id: "2",
    title: "Kiến thức thường trực",
    color: "#7ED321",
    icon: "school",
    description: "Kiến thức cần thiết thường xuyên",
    allowUpload: true,
    keyName: "kienthucthuongtruc",
  },
  {
    id: "3",
    title: "Đối tượng SQ, QNCN",
    color: "#F5A623",
    icon: "people",
    description: "Thông tin sĩ quan, quân nhân chuyên nghiệp",
    allowUpload: true,
    keyName: "doituongsqvaqncn",
  },
  {
    id: "4",
    title: "Đối tượng HLTPĐ",
    color: "#FF6B6B",
    icon: "training",
    description: "HSQ, BS thay phiên đảo",
    allowUpload: true,
    keyName: "doituonghltpd",
  },
  {
    id: "5",
    title: "Đối tượng HSQ, BS",
    color: "#D0021B",
    icon: "shield",
    description: "Hạ sĩ quan và binh sĩ",
    allowUpload: true,
    keyName: "hasiquanvabinhsi",
  },
  {
    id: "6",
    title: "ĐTĐ, ĐVM",
    color: "#9013FE",
    icon: "party",
    description: "Đảng viên và đảng viên mới",
    allowUpload: true,
    keyName: "dangvienvadangvienmoi",
  },
  {
    id: "7",
    title: "Đối tượng Đoàn viên",
    color: "#50E3C2",
    icon: "ribbon",
    description: "Thông tin về đoàn viên",
    allowUpload: true,
    keyName: "doituongdoanvien",
  },
  {
    id: "8",
    title: "Cấu hỏi kiến thức GDCT",
    color: "#B8E986",
    icon: "help-circle",
    description: "Câu hỏi giáo dục chính trị",
    allowUpload: true,
    keyName: "cauhoikienthucgdct",
  },
  {
    id: "9",
    title: "Cấu hỏi kiến thức pháp luật",
    color: "#4BD5EA",
    icon: "library",
    description: "Câu hỏi về pháp luật",
    allowUpload: true,
    keyName: "cauhoikienthucphapluat",
  },
];

export const documentSubcategories = [
  {
    id: "1-1",
    title: "Lịch sử",
    icon: "history",
    description: "Tài liệu lịch sử",
    parentId: "1",
    keyName: "lichsu",
  },
  {
    id: "1-2",
    title: "Nghị quyết",
    icon: "resolution",
    description: "Nghị quyết và quyết định",
    parentId: "1",
    keyName: "nghiquyet",
  },
  {
    id: "1-3",
    title: "Khoa học",
    icon: "science",
    description: "Tài liệu khoa học kỹ thuật",
    parentId: "1",
    keyName: "khoahoc",
  },
  {
    id: "1-4",
    title: "Kinh tế - Xã hội",
    icon: "economics",
    description: "Tài liệu kinh tế xã hội",
    parentId: "1",
    keyName: "kt-xh",
  },
  {
    id: "1-5",
    title: "Quân sự - Quốc phòng",
    icon: "qs-qp",
    description: "Quân sự - Quốc phòng",
    parentId: "1",
    keyName: "quansuvaquocphong",
  },
  {
    id: "1-6",
    title: "Văn hóa",
    icon: "culture",
    description: "Tài liệu văn hóa",
    parentId: "1",
    keyName: "vanhoa",
  },
  {
    id: "1-7",
    title: "Pháp luật",
    icon: "law",
    description: "Văn bản pháp luật",
    parentId: "1",
    keyName: "phapluat",
  },
  {
    id: "1-8",
    title: "Nghị định",
    icon: "decree",
    description: "Nghị định của Chính phủ",
    parentId: "1",
    keyName: "nghidinh",
  },
  {
    id: "1-9",
    title: "Thông tư",
    icon: "circular",
    description: "Thông tư hướng dẫn",
    parentId: "1",
    keyName: "thongtu",
  },
  {
    id: "1-10",
    title: "Hình ảnh",
    icon: "image",
    description: "Tài liệu hình ảnh",
    parentId: "1",
    keyName: "hinhanh",
  },
  {
    id: "1-11",
    title: "Video",
    icon: "video",
    description: "Tài liệu video",
    parentId: "1",
    keyName: "video",
  },
];
